name: microG Build

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v2

       - name: Create microG
         run: |
           rm -rf microG
           mkdir microG
           install -d out

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/microG-Installer microG

       - name: Create Sources
         run: |
           mkdir microG/sources

       - name: Clone Package Sources
         run: |
           git clone https://github.com/BiTGApps/microG-sources microG/sources/microG-sources

       - name: Build microG Package
         run: |
           cd microG
           . scripts/envsetup.sh && rm -rf scripts
           zip -qr9 MicroG-v1.5.zip * && cd ..
           cp -f microG/MicroG-v1.5.zip out

       - name: Sign microG Package
         run: |
           wget https://github.com/BiTGApps/BiTGApps/raw/master/tools/zipsigner/zipsigner.jar
           sudo java -jar zipsigner.jar out/MicroG-v1.5.zip out/MicroG-v1.5-Signed.zip
           rm -rf out/MicroG-v1.5.zip && mv -f out/MicroG-v1.5-Signed.zip out/MicroG-v1.5.zip

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Release Signed Package
         env:
           RELEASE: v1.5
         run: |
           github-release upload \
           --owner "BiTGApps" \
           --repo "microG-Installer" \
           --token "$TOKEN" \
           --tag "${RELEASE}" \
           --release-name "MicroG ${RELEASE}" \
           "out/MicroG-v1.5.zip"

       - name: Upload Build Artifact
         uses: actions/upload-artifact@v2
         with:
           name: microG-Build
           path: out/MicroG-v1.5.zip
